// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error_Code int32

const (
	Error_INTERNAL_SERVER_ERROR Error_Code = 0
	Error_NOT_FOUND             Error_Code = 1
	Error_REQUEST_MALFORMED     Error_Code = 2
	Error_UNAUTHORIZED          Error_Code = 3
	Error_ALREADY_REGISTERED    Error_Code = 4
	Error_BAD_CREDENTIALS       Error_Code = 5
)

var Error_Code_name = map[int32]string{
	0: "INTERNAL_SERVER_ERROR",
	1: "NOT_FOUND",
	2: "REQUEST_MALFORMED",
	3: "UNAUTHORIZED",
	4: "ALREADY_REGISTERED",
	5: "BAD_CREDENTIALS",
}

var Error_Code_value = map[string]int32{
	"INTERNAL_SERVER_ERROR": 0,
	"NOT_FOUND":             1,
	"REQUEST_MALFORMED":     2,
	"UNAUTHORIZED":          3,
	"ALREADY_REGISTERED":    4,
	"BAD_CREDENTIALS":       5,
}

func (x Error_Code) String() string {
	return proto.EnumName(Error_Code_name, int32(x))
}

func (Error_Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0, 0}
}

type Error struct {
	Code                 Error_Code `protobuf:"varint,1,opt,name=code,proto3,enum=pb.Error_Code" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() Error_Code {
	if m != nil {
		return m.Code
	}
	return Error_INTERNAL_SERVER_ERROR
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SaveResourceRequest struct {
	Value                string   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResourceRequest) Reset()         { *m = SaveResourceRequest{} }
func (m *SaveResourceRequest) String() string { return proto.CompactTextString(m) }
func (*SaveResourceRequest) ProtoMessage()    {}
func (*SaveResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *SaveResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResourceRequest.Unmarshal(m, b)
}
func (m *SaveResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResourceRequest.Marshal(b, m, deterministic)
}
func (m *SaveResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResourceRequest.Merge(m, src)
}
func (m *SaveResourceRequest) XXX_Size() int {
	return xxx_messageInfo_SaveResourceRequest.Size(m)
}
func (m *SaveResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResourceRequest proto.InternalMessageInfo

func (m *SaveResourceRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ListResourceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResourceRequest) Reset()         { *m = ListResourceRequest{} }
func (m *ListResourceRequest) String() string { return proto.CompactTextString(m) }
func (*ListResourceRequest) ProtoMessage()    {}
func (*ListResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *ListResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResourceRequest.Unmarshal(m, b)
}
func (m *ListResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResourceRequest.Marshal(b, m, deterministic)
}
func (m *ListResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResourceRequest.Merge(m, src)
}
func (m *ListResourceRequest) XXX_Size() int {
	return xxx_messageInfo_ListResourceRequest.Size(m)
}
func (m *ListResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListResourceRequest proto.InternalMessageInfo

type GetResourceRequest struct {
	ResourceId           string   `protobuf:"bytes,1,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResourceRequest) Reset()         { *m = GetResourceRequest{} }
func (m *GetResourceRequest) String() string { return proto.CompactTextString(m) }
func (*GetResourceRequest) ProtoMessage()    {}
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *GetResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResourceRequest.Unmarshal(m, b)
}
func (m *GetResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResourceRequest.Marshal(b, m, deterministic)
}
func (m *GetResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResourceRequest.Merge(m, src)
}
func (m *GetResourceRequest) XXX_Size() int {
	return xxx_messageInfo_GetResourceRequest.Size(m)
}
func (m *GetResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetResourceRequest proto.InternalMessageInfo

func (m *GetResourceRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

type DeleteResourceRequest struct {
	ResourceId           string   `protobuf:"bytes,1,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResourceRequest) Reset()         { *m = DeleteResourceRequest{} }
func (m *DeleteResourceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteResourceRequest) ProtoMessage()    {}
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4}
}

func (m *DeleteResourceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResourceRequest.Unmarshal(m, b)
}
func (m *DeleteResourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResourceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteResourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResourceRequest.Merge(m, src)
}
func (m *DeleteResourceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteResourceRequest.Size(m)
}
func (m *DeleteResourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResourceRequest proto.InternalMessageInfo

func (m *DeleteResourceRequest) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

type Resource struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Value                string   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Resource) Reset()         { *m = Resource{} }
func (m *Resource) String() string { return proto.CompactTextString(m) }
func (*Resource) ProtoMessage()    {}
func (*Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{5}
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Resource.Unmarshal(m, b)
}
func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Resource.Marshal(b, m, deterministic)
}
func (m *Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Resource.Merge(m, src)
}
func (m *Resource) XXX_Size() int {
	return xxx_messageInfo_Resource.Size(m)
}
func (m *Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_Resource proto.InternalMessageInfo

func (m *Resource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Resource) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ResourceList struct {
	List                 []*Resource `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResourceList) Reset()         { *m = ResourceList{} }
func (m *ResourceList) String() string { return proto.CompactTextString(m) }
func (*ResourceList) ProtoMessage()    {}
func (*ResourceList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{6}
}

func (m *ResourceList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceList.Unmarshal(m, b)
}
func (m *ResourceList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceList.Marshal(b, m, deterministic)
}
func (m *ResourceList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceList.Merge(m, src)
}
func (m *ResourceList) XXX_Size() int {
	return xxx_messageInfo_ResourceList.Size(m)
}
func (m *ResourceList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceList.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceList proto.InternalMessageInfo

func (m *ResourceList) GetList() []*Resource {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Error_Code", Error_Code_name, Error_Code_value)
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*SaveResourceRequest)(nil), "pb.SaveResourceRequest")
	proto.RegisterType((*ListResourceRequest)(nil), "pb.ListResourceRequest")
	proto.RegisterType((*GetResourceRequest)(nil), "pb.GetResourceRequest")
	proto.RegisterType((*DeleteResourceRequest)(nil), "pb.DeleteResourceRequest")
	proto.RegisterType((*Resource)(nil), "pb.Resource")
	proto.RegisterType((*ResourceList)(nil), "pb.ResourceList")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x8e, 0xd2, 0x50,
	0x14, 0x9e, 0x96, 0x82, 0x72, 0x86, 0x61, 0x3a, 0x87, 0x01, 0x3b, 0x68, 0x26, 0xa4, 0x2b, 0x32,
	0x26, 0x05, 0xd1, 0xc4, 0xc4, 0x5d, 0xa5, 0x77, 0x90, 0xc8, 0x94, 0x78, 0x5b, 0x4c, 0xd4, 0x45,
	0x53, 0xe0, 0x4a, 0x9a, 0x74, 0x28, 0xb6, 0x17, 0x12, 0x63, 0xdc, 0xb8, 0xf0, 0x05, 0x7c, 0x2f,
	0x37, 0xbe, 0x82, 0x4f, 0xe1, 0xca, 0xf4, 0x32, 0x9d, 0x1f, 0x84, 0x85, 0xcb, 0x7b, 0xbe, 0x9f,
	0xfb, 0xe5, 0x3b, 0x39, 0x70, 0x90, 0xf0, 0x28, 0xf6, 0x67, 0xcc, 0x58, 0xc4, 0x11, 0x8f, 0x50,
	0x5e, 0x8c, 0xeb, 0x0f, 0x67, 0x51, 0x34, 0x0b, 0x59, 0x4b, 0x4c, 0xc6, 0xcb, 0x8f, 0x2d, 0x76,
	0xb9, 0xe0, 0x9f, 0xd7, 0x84, 0xfa, 0xa3, 0x2b, 0xd0, 0x5f, 0x04, 0x2d, 0x7f, 0x3e, 0x8f, 0xb8,
	0xcf, 0x83, 0x68, 0x9e, 0xac, 0x51, 0xfd, 0xa7, 0x04, 0x79, 0x12, 0xc7, 0x51, 0x8c, 0x3a, 0x28,
	0x93, 0x68, 0xca, 0x34, 0xa9, 0x21, 0x35, 0xcb, 0x9d, 0xb2, 0xb1, 0x18, 0x1b, 0x02, 0x30, 0xba,
	0xd1, 0x94, 0x51, 0x81, 0xa1, 0x06, 0xf7, 0x2e, 0x59, 0x92, 0xf8, 0x33, 0xa6, 0xc9, 0x0d, 0xa9,
	0x59, 0xa4, 0xd9, 0x53, 0xff, 0x2e, 0x81, 0x92, 0x12, 0xf1, 0x04, 0xaa, 0x7d, 0xdb, 0x25, 0xd4,
	0x36, 0x07, 0x9e, 0x43, 0xe8, 0x5b, 0x42, 0x3d, 0x42, 0xe9, 0x90, 0xaa, 0x7b, 0x78, 0x00, 0x45,
	0x7b, 0xe8, 0x7a, 0xe7, 0xc3, 0x91, 0x6d, 0xa9, 0x12, 0x56, 0xe1, 0x88, 0x92, 0x37, 0x23, 0xe2,
	0xb8, 0xde, 0x85, 0x39, 0x38, 0x1f, 0xd2, 0x0b, 0x62, 0xa9, 0x32, 0xaa, 0x50, 0x1a, 0xd9, 0xe6,
	0xc8, 0x7d, 0x35, 0xa4, 0xfd, 0xf7, 0xc4, 0x52, 0x73, 0x58, 0x03, 0x34, 0x07, 0x94, 0x98, 0xd6,
	0x3b, 0x8f, 0x92, 0x5e, 0xdf, 0x71, 0x09, 0x25, 0x96, 0xaa, 0x60, 0x05, 0x0e, 0x5f, 0x9a, 0x96,
	0xd7, 0xa5, 0xc4, 0x22, 0xb6, 0xdb, 0x37, 0x07, 0x8e, 0x9a, 0xd7, 0x1f, 0x43, 0xc5, 0xf1, 0x57,
	0x8c, 0xb2, 0x24, 0x5a, 0xc6, 0x13, 0x46, 0xd9, 0xa7, 0x25, 0x4b, 0x38, 0x1e, 0x43, 0x7e, 0xe5,
	0x87, 0x4b, 0xa6, 0x15, 0x44, 0xee, 0xf5, 0x43, 0xaf, 0x42, 0x65, 0x10, 0x24, 0x7c, 0x83, 0xac,
	0x3f, 0x03, 0xec, 0xb1, 0xcd, 0x29, 0x9e, 0x02, 0xc4, 0x57, 0xa3, 0xfe, 0x54, 0xd4, 0x54, 0xa4,
	0xb7, 0x26, 0xfa, 0x73, 0xa8, 0x5a, 0x2c, 0x64, 0x9c, 0xfd, 0xaf, 0xb0, 0x0d, 0xf7, 0x33, 0x09,
	0x96, 0x41, 0x0e, 0x32, 0x8e, 0x1c, 0x4c, 0x77, 0xe4, 0x6e, 0x43, 0x29, 0x53, 0xa4, 0xf9, 0xb1,
	0x01, 0x4a, 0x18, 0x24, 0x5c, 0x93, 0x1a, 0xb9, 0xe6, 0x7e, 0xa7, 0x94, 0xee, 0xee, 0x3a, 0x84,
	0x40, 0x3a, 0x7f, 0x64, 0x38, 0xcc, 0x46, 0x0e, 0x8b, 0x57, 0xc1, 0x84, 0x61, 0x17, 0x94, 0xb4,
	0x2a, 0x7c, 0x90, 0xf2, 0xb7, 0x94, 0x56, 0xbf, 0x63, 0xa4, 0x1f, 0x7f, 0xfb, 0xf5, 0xfb, 0x87,
	0x5c, 0xd6, 0x8b, 0xad, 0x2c, 0xfb, 0x0b, 0xe9, 0x0c, 0x9f, 0x80, 0x22, 0x22, 0x08, 0x93, 0x2d,
	0x65, 0x6e, 0x98, 0xec, 0xb5, 0x25, 0x24, 0x50, 0xe8, 0x31, 0x6e, 0x86, 0x21, 0xd6, 0x52, 0xec,
	0xdf, 0xaa, 0xeb, 0xea, 0x6d, 0x4d, 0x6a, 0xaa, 0x1f, 0x89, 0xcf, 0xf7, 0xf1, 0xe6, 0x73, 0x7c,
	0x0d, 0xb9, 0x1e, 0xe3, 0x3b, 0x3d, 0xee, 0xfe, 0x7b, 0x2a, 0xf4, 0x1a, 0xd6, 0xae, 0xf5, 0xad,
	0x2f, 0x37, 0x2b, 0xf8, 0x8a, 0x1f, 0xa0, 0xb0, 0x5e, 0x1e, 0x9e, 0xa4, 0xba, 0xad, 0x8b, 0xac,
	0xd7, 0x8c, 0xf5, 0x2d, 0x19, 0xd9, 0xa1, 0x19, 0x24, 0x3d, 0xb4, 0xcc, 0xfc, 0x6c, 0x87, 0xf9,
	0xb8, 0x20, 0xf8, 0x4f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x6b, 0x69, 0x43, 0xbb, 0x03,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ResourceServiceClient interface {
	Save(ctx context.Context, in *SaveResourceRequest, opts ...grpc.CallOption) (*Resource, error)
	List(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (ResourceService_ListClient, error)
	GetAll(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*ResourceList, error)
	Get(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Resource, error)
	Delete(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type resourceServiceClient struct {
	cc *grpc.ClientConn
}

func NewResourceServiceClient(cc *grpc.ClientConn) ResourceServiceClient {
	return &resourceServiceClient{cc}
}

func (c *resourceServiceClient) Save(ctx context.Context, in *SaveResourceRequest, opts ...grpc.CallOption) (*Resource, error) {
	out := new(Resource)
	err := c.cc.Invoke(ctx, "/pb.ResourceService/Save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) List(ctx context.Context, in *ListResourceRequest, opts ...grpc.CallOption) (ResourceService_ListClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ResourceService_serviceDesc.Streams[0], "/pb.ResourceService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &resourceServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ResourceService_ListClient interface {
	Recv() (*Resource, error)
	grpc.ClientStream
}

type resourceServiceListClient struct {
	grpc.ClientStream
}

func (x *resourceServiceListClient) Recv() (*Resource, error) {
	m := new(Resource)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *resourceServiceClient) GetAll(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*ResourceList, error) {
	out := new(ResourceList)
	err := c.cc.Invoke(ctx, "/pb.ResourceService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) Get(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*Resource, error) {
	out := new(Resource)
	err := c.cc.Invoke(ctx, "/pb.ResourceService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourceServiceClient) Delete(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ResourceService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourceServiceServer is the server API for ResourceService service.
type ResourceServiceServer interface {
	Save(context.Context, *SaveResourceRequest) (*Resource, error)
	List(*ListResourceRequest, ResourceService_ListServer) error
	GetAll(context.Context, *GetResourceRequest) (*ResourceList, error)
	Get(context.Context, *GetResourceRequest) (*Resource, error)
	Delete(context.Context, *DeleteResourceRequest) (*empty.Empty, error)
}

// UnimplementedResourceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedResourceServiceServer struct {
}

func (*UnimplementedResourceServiceServer) Save(ctx context.Context, req *SaveResourceRequest) (*Resource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Save not implemented")
}
func (*UnimplementedResourceServiceServer) List(req *ListResourceRequest, srv ResourceService_ListServer) error {
	return status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedResourceServiceServer) GetAll(ctx context.Context, req *GetResourceRequest) (*ResourceList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (*UnimplementedResourceServiceServer) Get(ctx context.Context, req *GetResourceRequest) (*Resource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedResourceServiceServer) Delete(ctx context.Context, req *DeleteResourceRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterResourceServiceServer(s *grpc.Server, srv ResourceServiceServer) {
	s.RegisterService(&_ResourceService_serviceDesc, srv)
}

func _ResourceService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).Save(ctx, req.(*SaveResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListResourceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResourceServiceServer).List(m, &resourceServiceListServer{stream})
}

type ResourceService_ListServer interface {
	Send(*Resource) error
	grpc.ServerStream
}

type resourceServiceListServer struct {
	grpc.ServerStream
}

func (x *resourceServiceListServer) Send(m *Resource) error {
	return x.ServerStream.SendMsg(m)
}

func _ResourceService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).GetAll(ctx, req.(*GetResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).Get(ctx, req.(*GetResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ResourceService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourceServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ResourceService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourceServiceServer).Delete(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ResourceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Save",
			Handler:    _ResourceService_Save_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _ResourceService_GetAll_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ResourceService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ResourceService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "List",
			Handler:       _ResourceService_List_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "storage.proto",
}
